export let categorias = [
    "APIS",
    "AWS",
    "BROWSER EXTENSIONS",
    "CODING PRACTICE",
    "COLOR PALETTES",
    "COURSES",
    "CSS",
    "CSS TOOLS",
    "DATA STRUCTURES & ALGORITHMS",
    "DEVOPS",
    "DOCUMENTATION",
    "ERRORS | SOLUTIONS",
    "FONTS",
    "GIT",
    "HTML",
    "ICONS",
    "IMAGES",
    "IMAGES TOOLS",
    "INTERVIEWS",
    "JAVA",
    "JS",
    "JS LIBRARIES",
    "MARKDOWN",
    "NODEJS-DATABASE",
    "NODEJS-EXPRESS",
    "OTHERS",
    "PYTHON",
    "REACT",
    "REACT LIBRARIES",
    "REGULAR EXPRESSIONS",
    "REPOSITORIES",
    "SQL",
    "TUTORIALS",
    "USEFUL TOOLS",
    "UX",
    "VSCODE EXTENSIONS"
];
