const category = "DATA STRUCTURES & ALGORITHMS"
export const dsa = [
    {
        name: "Big O Notation - Full Course",
        url: "https://www.youtube.com/watch?v=Mo4vesaut8g",
        category
    },
    {
        name: "The Algorithms",
        url: "https://github.com/TheAlgorithms",
        category
    },
    {
        name: "Big O Cheat Sheet ZTM",
        url: "https://zerotomastery.io/cheatsheets/big-o-cheat-sheet/?utm_source=udemy&utm_medium=coursecontent",
        category
    },
    {
        name: "Big O Cheat Sheet",
        url: "https://www.bigocheatsheet.com/",
        category
    },
    {
        name: "Data Structures Diagram",
        url: "https://coggle.it/diagram/W5E5tqYlrXvFJPsq/t/master-the-interview-click-here-for-course-link/c25f98c73a03f5b1107cd0e2f4bce29c9d78e31655e55cb0b785d56f0036c9d1",
        category
    },
    {
        name: "Big O Notation in JavaScript",
        url: "https://www.doabledanny.com/big-o-notation-in-javascript",
        category
    },
    {
        name: "JavaScript Algorithms and Data Structures",
        url: "https://github.com/trekhleb/javascript-algorithms",
        category
    },
    {
        name: "Learn DS & Algorithms | Programiz",
        url: "https://www.programiz.com/dsa",
        category
    },
    {
        name: "Trees Slides",
        url: "http://www.itnuevolaredo.edu.mx/takeyas/Apuntes/Estructura%20de%20Datos/Apuntes/07-ABB.pdf",
        category
    },
    {
        name: "VisuAlgo | visualising data structures and algorithms through animation",
        url: "https://visualgo.net/en",
        category
    },
    {
        name: "Data Structure Visualizations",
        url: "https://www.cs.usfca.edu/~galles/visualization/Algorithms.html",
        category
    },
    {
        name: "BINARY SEARCH TREE AVL TREE | Visual Tool",
        url: "https://visualgo.net/en/bst?slide=1",
        category
    },
    {
        name: "LINKED LIST STACK QUEUE DLL DEQUE | Visual Tool",
        url: "https://visualgo.net/en/list",
        category
    },
    {
        name: "Heap Sort | Visual Explanation",
        url: "https://brilliant.org/wiki/heap-sort/",
        category
    },
    {
        name: "Implement Queue using Stacks | exercise",
        url: "https://leetcode.com/problems/implement-queue-using-stacks/description/",
        category
    },
    {
        name: "Two Sum | array exercise",
        url: "https://leetcode.com/problems/two-sum/description/",
        category
    },
    {
        name: "Maximum Subarray | array exercise",
        url: "https://leetcode.com/problems/maximum-subarray/description/",
        category
    },
    {
        name: "Move Zeroes | array exercise",
        url: "https://leetcode.com/problems/move-zeroes/description/",
        category
    },
    {
        name: "Contains Duplicate | array exercise",
        url: "https://leetcode.com/problems/contains-duplicate/description/",
        category
    },
    {
        name: "Rotate Array | array exercise",
        url: "https://leetcode.com/problems/rotate-array/description/",
        category
    },
    {
        name: "Longest Word | array exercise",
        url: "https://coderbyte.com/editor/Longest%20Word:JavaScript",
        category
    },


];
